# Snabb benchmark report

This is an automatically-generated report that describes an
automatically-executed benchmarking campaign.

## Initialization

```{r}
knitr::opts_chunk$set(error=TRUE)
library(ggplot2)
dat <- read.csv("bench.csv")
d <- as.data.frame(dat)

iperf <- subset(d, subset=(benchmark == "iperf"))

l2fwd <- subset(d, subset=(benchmark=="l2fwd"))
summary(d)
```

## Iperf

These benchmarks summarize iperf performance with multiple
configurations and guest kernel versions.

### Raw data

```{r}
p <- ggplot(iperf, aes(y=score, x=1, color=kernel))
p <- p + geom_jitter()
p + ggtitle("iperf raw data (colored by kernel version)")
```

### Split by config

```{r}
p <- ggplot(iperf, aes(x=config, y=score, color=kernel))
p <- p + geom_jitter()
p + ggtitle("iperf by config")
```

### Boxplot

```{r}
p <- ggplot(iperf, aes(x=config, y=score, color=kernel))
p <- p + geom_boxplot()
p <- p + facet_grid(. ~ kernel)
p + ggtitle("iperf by kernel")
```

### Tukey test

```{r}
TukeyHSD(aov(score ~ config, data=iperf))
```

### Boxplot

```{r}
p <- ggplot(l2fwd, aes(x=config, y=score, color=kernel))
p <- p + geom_boxplot()
p <- p + facet_grid(. ~ kernel)
p + ggtitle("l2fwd boxplot")
```

### Tukey test

```{r}
TukeyHSD(aov(score ~ config, data=l2fwd))
```
